// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameClientReq.proto

#include "GameClientReq.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace protoAuth {
constexpr GameClientReq::GameClientReq(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(0)

  , ivalue_(0)
  , jvalue_(0){}
struct GameClientReqDefaultTypeInternal {
  constexpr GameClientReqDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~GameClientReqDefaultTypeInternal() {}
  union {
    GameClientReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT GameClientReqDefaultTypeInternal _GameClientReq_default_instance_;
}  // namespace protoAuth
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_GameClientReq_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_GameClientReq_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_GameClientReq_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_GameClientReq_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protoAuth::GameClientReq, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protoAuth::GameClientReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protoAuth::GameClientReq, id_),
  PROTOBUF_FIELD_OFFSET(::protoAuth::GameClientReq, ivalue_),
  PROTOBUF_FIELD_OFFSET(::protoAuth::GameClientReq, jvalue_),
  0,
  1,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::protoAuth::GameClientReq)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protoAuth::_GameClientReq_default_instance_),
};

const char descriptor_table_protodef_GameClientReq_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023GameClientReq.proto\022\tprotoAuth\"\304\001\n\rGam"
  "eClientReq\0221\n\002id\030\001 \002(\0162%.protoAuth.GameC"
  "lientReq.eMessageType\022\016\n\006iValue\030\002 \002(\005\022\016\n"
  "\006jValue\030\003 \002(\005\"`\n\014eMessageType\022\013\n\007GAMEWON"
  "\020\000\022\014\n\010GAMELOST\020\001\022\007\n\003HIT\020\002\022\n\n\006NOTHIT\020\003\022\017\n"
  "\013PLAYER1TURN\020\004\022\017\n\013PLAYER2TURN\020\005"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_GameClientReq_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GameClientReq_2eproto = {
  false, false, 231, descriptor_table_protodef_GameClientReq_2eproto, "GameClientReq.proto", 
  &descriptor_table_GameClientReq_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_GameClientReq_2eproto::offsets,
  file_level_metadata_GameClientReq_2eproto, file_level_enum_descriptors_GameClientReq_2eproto, file_level_service_descriptors_GameClientReq_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_GameClientReq_2eproto_getter() {
  return &descriptor_table_GameClientReq_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_GameClientReq_2eproto(&descriptor_table_GameClientReq_2eproto);
namespace protoAuth {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameClientReq_eMessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_GameClientReq_2eproto);
  return file_level_enum_descriptors_GameClientReq_2eproto[0];
}
bool GameClientReq_eMessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr GameClientReq_eMessageType GameClientReq::GAMEWON;
constexpr GameClientReq_eMessageType GameClientReq::GAMELOST;
constexpr GameClientReq_eMessageType GameClientReq::HIT;
constexpr GameClientReq_eMessageType GameClientReq::NOTHIT;
constexpr GameClientReq_eMessageType GameClientReq::PLAYER1TURN;
constexpr GameClientReq_eMessageType GameClientReq::PLAYER2TURN;
constexpr GameClientReq_eMessageType GameClientReq::eMessageType_MIN;
constexpr GameClientReq_eMessageType GameClientReq::eMessageType_MAX;
constexpr int GameClientReq::eMessageType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class GameClientReq::_Internal {
 public:
  using HasBits = decltype(std::declval<GameClientReq>()._has_bits_);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_ivalue(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_jvalue(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

GameClientReq::GameClientReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:protoAuth.GameClientReq)
}
GameClientReq::GameClientReq(const GameClientReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&jvalue_) -
    reinterpret_cast<char*>(&id_)) + sizeof(jvalue_));
  // @@protoc_insertion_point(copy_constructor:protoAuth.GameClientReq)
}

void GameClientReq::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&jvalue_) -
    reinterpret_cast<char*>(&id_)) + sizeof(jvalue_));
}

GameClientReq::~GameClientReq() {
  // @@protoc_insertion_point(destructor:protoAuth.GameClientReq)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void GameClientReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GameClientReq::ArenaDtor(void* object) {
  GameClientReq* _this = reinterpret_cast< GameClientReq* >(object);
  (void)_this;
}
void GameClientReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GameClientReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GameClientReq::Clear() {
// @@protoc_insertion_point(message_clear_start:protoAuth.GameClientReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&jvalue_) -
        reinterpret_cast<char*>(&id_)) + sizeof(jvalue_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameClientReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .protoAuth.GameClientReq.eMessageType id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::protoAuth::GameClientReq_eMessageType_IsValid(val))) {
            _internal_set_id(static_cast<::protoAuth::GameClientReq_eMessageType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // required int32 iValue = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_ivalue(&has_bits);
          ivalue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required int32 jValue = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_jvalue(&has_bits);
          jvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GameClientReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protoAuth.GameClientReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .protoAuth.GameClientReq.eMessageType id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_id(), target);
  }

  // required int32 iValue = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_ivalue(), target);
  }

  // required int32 jValue = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_jvalue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoAuth.GameClientReq)
  return target;
}

size_t GameClientReq::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:protoAuth.GameClientReq)
  size_t total_size = 0;

  if (_internal_has_id()) {
    // required .protoAuth.GameClientReq.eMessageType id = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_id());
  }

  if (_internal_has_ivalue()) {
    // required int32 iValue = 2;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_ivalue());
  }

  if (_internal_has_jvalue()) {
    // required int32 jValue = 3;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_jvalue());
  }

  return total_size;
}
size_t GameClientReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoAuth.GameClientReq)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required .protoAuth.GameClientReq.eMessageType id = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_id());

    // required int32 iValue = 2;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_ivalue());

    // required int32 jValue = 3;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_jvalue());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameClientReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GameClientReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameClientReq::GetClassData() const { return &_class_data_; }

void GameClientReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<GameClientReq *>(to)->MergeFrom(
      static_cast<const GameClientReq &>(from));
}


void GameClientReq::MergeFrom(const GameClientReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoAuth.GameClientReq)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000002u) {
      ivalue_ = from.ivalue_;
    }
    if (cached_has_bits & 0x00000004u) {
      jvalue_ = from.jvalue_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameClientReq::CopyFrom(const GameClientReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoAuth.GameClientReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameClientReq::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void GameClientReq::InternalSwap(GameClientReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameClientReq, jvalue_)
      + sizeof(GameClientReq::jvalue_)
      - PROTOBUF_FIELD_OFFSET(GameClientReq, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameClientReq::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_GameClientReq_2eproto_getter, &descriptor_table_GameClientReq_2eproto_once,
      file_level_metadata_GameClientReq_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protoAuth
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protoAuth::GameClientReq* Arena::CreateMaybeMessage< ::protoAuth::GameClientReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protoAuth::GameClientReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
